export const catsData = [
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "/catimages/angry.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody", "insomniac"],
    isGif: false,
    image: "/catimages/angry2.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "/catimages/angry3.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["confused", "sad"],
    isGif: false,
    image: "/catimages/confused.jpeg",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant", "moody"],
    isGif: false,
    image: "/catimages/dominant.jpeg",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy", "relaxed"],
    isGif: false,
    image: "/catimages/happy.jpeg",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "/catimages/hungry.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "/catimages/hungry1.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "/catimages/insomnia.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "/catimages/insomnia1.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "/catimages/lazy.jpeg",
    alt: "A cat looking lazy",
  },
  {
    emotionTags: ["scared"],
    isGif: false,
    image: "/catimages/nervous.jpeg",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "/catimages/sad.jpeg",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["sad", "moody"],
    isGif: false,
    image: "/catimages/sad1.jpeg",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "/catimages/angry.gif",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "/catimages/angry2.gif",
    alt: "A cat looking angry",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "./catimages/confused2.gif",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "/catimages/dominant.gif",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy"],
    isGif: true,
    image: "/catimages/happy.gif",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry", "sad", "confused"],
    isGif: true,
    image: "/catimages/confused.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "/catimages/hungry.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "/catimages/hungry2.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac", "scared"],
    isGif: true,
    image: "/catimages/insomnia2.gif",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "/catimages/lazy.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "/catimages/relaxed2.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["scared", "sad"],
    isGif: true,
    image: "/catimages/nervous.gif",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["scared"],
    isGif: true,
    image: "/catimages/nervous2.gif",
    alt: "A cat looking scared",
  },
  {
    emotionTags: ["sad"],
    isGif: true,
    image: "/catimages/sad.gif",
    alt: "A cat looking sad",
  },
];
